### ISSUE TITLE
Kurzreview

### ISSUE THREAD

**Issue by signalwerk** [severinkilchhofer/portfolio#1]
## Hallo Severin
Ich habe mir kurz dein Portfolio durchgeschaut. Ich habe nur kurz drauf geschaut, da ich davon ausgehe, dass du noch nicht fertig bist. Hier vielleicht ein paar Inputs (eher technisch):

* ich würde in der Benotung nur die «Experimentelles Erzählen»-Seite beurteilen, da die andere Seite einerseits nicht Aufgabe wäre, andererseits ja noch nicht fertig ist. ok? 
* Die Scroll-Down-Navigation finde ich grundsätzlich gut. Allenfalls kannst du deinen Seitenaufbau so machen, dass die Punkte und die Bilder nicht im Konflikt sind.
* Einige Dinge, die wir schon besprochen hatten: Typografie vom Text eventuell noch einmal verfeinern und mit mehr Struktur/Abstufung versehen.
* In den Titeln nach dem Datum steht ein Gedankenstrich. Du machst jetzt ein Divis. Schau mal [heir](https://github.com/logrinto/webtypo/wiki/Divis-vs.-Halbgeviert)
* Farbkontrast von Seitentitel «Experimentelles Erzählen» zum Hintergrund erhöhen.

Wenn du einen  Kommentar oder ein Problem hast, bitte hier antworten.

**Comment by severinkilchhofer** [comment]
Hoi Stefan
Besten Dank für dein Feedback.
Wie du gesehen hast arbeite ich noch ein meine Projekt und möchte jetzt noch eine Produktseite erstellen die unser Spiel zeigt.
